name = "young-capital-advisory"
compatibility_date = "2026-01-23"
workers_dev = true

[assets]
directory = "./public"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
